#!/usr/bin/env bash
# version: 4.1.0

set -eo pipefail

function convert_to_file_content_env() {
  local name=$(echo "$1" | tr '-' '_' | tr '.' '_' | tr '[:lower:]' '[:upper:]')
  
  echo "FILE_CONTENT_${name}_BASE64"
}

function help() {
    echo "Usage: `basename $0` PROJECT_NAME [FILES_PATTERN]"
    echo "example: `basename $0` project '/tmp/*.yml'"
}

function parse_arguments() {
    while getopts "co:h-:" option; do
        case "${option}" in
            -)
                case "${OPTARG}" in
                    append-ci-envs)
                        export ENV_PROJECT_PATH="${CI_PROJECT_PATH}"
                        export ENV_AUTHOR_USERNAME="${GITLAB_USER_LOGIN}"
                        export ENV_AUTHOR="${CI_COMMIT_AUTHOR}"
                        export ENV_MESSAGE="${CI_COMMIT_MESSAGE}"
                        export ENV_COMMIT_SHA="${CI_COMMIT_SHORT_SHA}"
                        ;;
                    help)
                        help
                        ;;
                esac;;
            h)
                help
                exit
                ;;
            *)
                help
                exit 1
                ;;
        esac
    done
}

parse_arguments "$@"
shift $(($OPTIND - 1))

export project_name="$1"
files_pattern="$2"
chunk_max_length=9999

if [ -z "${project_name}" ]; then
  help

  exit 1
fi

: ${JOB_NAME:="trigger"}

contents=$(yq e '.stages[0] = "trigger"' -n)
contents=$(echo "$contents" | yq e '.'${JOB_NAME}'.stage = "trigger"')
contents=$(echo "$contents" | yq e '.'${JOB_NAME}'.trigger.project = strenv(project_name)')
contents=$(echo "$contents" | yq e '.'${JOB_NAME}'.trigger.strategy = "depend"')

for file in ${files_pattern}; do
  export file_name=$(basename "${file}")
  export file_content_base64=$(cat "${file}" | base64 -w 0)
  export chunks=$(echo "${file_content_base64}" | fold -w "${chunk_max_length}")
  export chunks_length=$(echo "${chunks}" | wc -l)

  if [ "${chunks_length}" -gt 1 ]; then
    i=1
    for chunk in ${chunks}; do 
      export key="$(convert_to_file_content_env "${file_name}_part${i}")"
      export value="${chunk}"
      contents=$(echo "$contents" | yq e '.'${JOB_NAME}'.variables += {strenv(key):strenv(value)}')
      i=$((i+1))
    done
  else
    export key="$(convert_to_file_content_env "${file_name}")"
    contents=$(echo "$contents" | yq e '.'${JOB_NAME}'.variables += {strenv(key):strenv(file_content_base64)}')
  fi
done

for env in ${!ENV*}; do
  export key="${env:4}"
  export value=$(printenv "${env}")

  contents=$(echo "$contents" | yq e '.'${JOB_NAME}'.variables += {strenv(key):strenv(value)}')
done

echo "$contents"
