#!/usr/bin/env sh

repo=$1
type=$2

if [ "$repo" = "" ]; then
    current_script=`basename $0`
	echo "Usage: $current_script repo [type]"
    echo
	echo "example #1: $current_script php/php-src tags"
    echo "example #2: $current_script bitnami-labs/sealed-secrets"
    echo "example #3: curl -s \$REMOTE_URL/$current_script | sh -s bitnami-labs/sealed-secrets"

    exit 1
fi

url="https://github.com/$repo"

fetch()
{
    if command -v curl > /dev/null
    then
        contents=$(curl -s -L "$1")
    elif command -v wget > /dev/null
    then
        contents=$(wget -q -O - "$1")
    fi

    echo "$contents"
}

if [ "$type" = "" ]; then
    contents=$(fetch "$url/releases/latest")
    version=$(echo $contents | sed -n 's#^.*/tree/\([^"]*\).*$#\1#p')
elif [ "$type" = "tags" ]; then
    contents=$(fetch "$url/tags")
    version=$(echo $contents | sed -n 's/^.*class="Link--primary">\([^<]*\).*$/\1/p' | sort -r | head -n 1)
fi

echo $version
